# -*- coding: utf-8 -*-
"""Brain_Tumor_Segmentation_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nRJatqMX384XnZjb4mR4jYduiBzn8ABc
"""

!pip install tensorflow opencv-python matplotlib seaborn scikit-learn pillow

import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from glob import glob
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator

print("Libraries Imported Successfully")

import tensorflow as tf

from tensorflow.keras.models import Model

from tensorflow.keras.layers import (
    Input,
    Conv2D,
    MaxPooling2D,
    UpSampling2D,
    concatenate,
    Dense,
    Dropout,
    GlobalAveragePooling2D
)

from tensorflow.keras.optimizers import Adam

import zipfile

zip_ref = zipfile.ZipFile('/content/drive/MyDrive/Colab Notebooks/archive (7).zip')
zip_ref.extractall('/content/dataset')
zip_ref.close()

print("Dataset Extracted")

os.listdir('/content/dataset')

train_path = '/content/dataset/Training'
test_path = '/content/dataset/Testing'

print(os.listdir(train_path))

for category in os.listdir(train_path):
    print(category, len(os.listdir(os.path.join(train_path, category))))

for category in os.listdir(test_path):
    print(category, len(os.listdir(os.path.join(test_path, category))))

categories = os.listdir(train_path)

plt.figure(figsize=(12,8))

for i, category in enumerate(categories):

    folder_path = os.path.join(train_path, category)
    image_name = os.listdir(folder_path)[0]

    image_path = os.path.join(folder_path, image_name)

    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.subplot(2,2,i+1)
    plt.imshow(image)
    plt.title(category)
    plt.axis('off')

plt.tight_layout()
plt.show()

IMG_SIZE = 96

def preprocess_image(image_path):

    image = cv2.imread(image_path)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))

    image = image / 255.0

    return image

X = []
y = []

categories = os.listdir(train_path)

for category in categories:

    folder_path = os.path.join(train_path, category)

    label = categories.index(category)

    for image_name in tqdm(os.listdir(folder_path)):

        image_path = os.path.join(folder_path, image_name)

        image = preprocess_image(image_path)

        X.append(image)
        y.append(label)

X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.1,
    height_shift_range=0.1
)

plt.figure(figsize=(10,10))

for i in range(9):

    plt.subplot(3,3,i+1)

    plt.imshow(X_train[i])

    plt.axis('off')

plt.show()

X_uint8 = (X * 255).astype(np.uint8)

def generate_mask(image):

    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

    blur = cv2.GaussianBlur(gray, (5,5), 0)

    _, thresh = cv2.threshold(
        blur,
        45,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    kernel = np.ones((3,3), np.uint8)

    mask = cv2.morphologyEx(
        thresh,
        cv2.MORPH_OPEN,
        kernel
    )

    return mask

masks = []

for image in tqdm(X_uint8):

    mask = generate_mask(image)

    masks.append(mask)

masks = np.array(masks)

print(masks.shape)

plt.figure(figsize=(12,8))

for i in range(3):

    plt.subplot(3,2,2*i+1)

    plt.imshow(X[i])

    plt.title("Original MRI")

    plt.axis('off')



    plt.subplot(3,2,2*i+2)

    plt.imshow(masks[i], cmap='gray')

    plt.title("Generated Mask")

    plt.axis('off')

plt.tight_layout()

plt.show()

masks = masks / 255.0

masks = np.expand_dims(masks, axis=-1)

print(masks.shape)

X_seg_train, X_seg_val, y_seg_train, y_seg_val = train_test_split(
    X,
    masks,
    test_size=0.2,
    random_state=42
)

#Dice Coefficient Function

def dice_coefficient(y_true, y_pred):

    smooth = 1e-6

    y_true_f = tf.keras.backend.flatten(y_true)
    y_pred_f = tf.keras.backend.flatten(y_pred)

    intersection = tf.keras.backend.sum(
        y_true_f * y_pred_f
    )

    return (
        2. * intersection + smooth
    ) / (
        tf.keras.backend.sum(y_true_f)
        +
        tf.keras.backend.sum(y_pred_f)
        +
        smooth
    )

#IoU Metric
def iou_metric(y_true, y_pred):

    smooth = 1e-6

    intersection = tf.keras.backend.sum(
        y_true * y_pred
    )

    union = (
        tf.keras.backend.sum(y_true)
        +
        tf.keras.backend.sum(y_pred)
        -
        intersection
    )

    return (
        intersection + smooth
    ) / (
        union + smooth
    )

#U-Net Architecture
def build_unet(input_shape):

    inputs = Input(input_shape)


    # Encoder

    c1 = Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same'
    )(inputs)

    c1 = Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same'
    )(c1)

    p1 = MaxPooling2D((2,2))(c1)



    c2 = Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    )(p1)

    c2 = Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    )(c2)

    p2 = MaxPooling2D((2,2))(c2)



    # Bottleneck

    bn = Conv2D(
        128,
        (3,3),
        activation='relu',
        padding='same'
    )(p2)

    bn = Conv2D(
        128,
        (3,3),
        activation='relu',
        padding='same'
    )(bn)



    # Decoder

    u1 = UpSampling2D((2,2))(bn)

    u1 = concatenate([u1, c2])

    c3 = Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    )(u1)

    c3 = Conv2D(
        64,
        (3,3),
        activation='relu',
        padding='same'
    )(c3)



    u2 = UpSampling2D((2,2))(c3)

    u2 = concatenate([u2, c1])

    c4 = Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same'
    )(u2)

    c4 = Conv2D(
        32,
        (3,3),
        activation='relu',
        padding='same'
    )(c4)



    outputs = Conv2D(
        1,
        (1,1),
        activation='sigmoid'
    )(c4)



    model = Model(inputs, outputs)

    return model

#Initialize Model
unet_model = build_unet(
    (96,96,3)
)

#Compile Model
unet_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=[
        'accuracy',
        dice_coefficient,
        iou_metric
    ]
)

#Model Summary
unet_model.summary()

print(unet_model)

import gc

gc.collect()

tf.keras.backend.clear_session()

#Train U-Net
history = unet_model.fit(
    X_seg_train,
    y_seg_train,
    validation_data=(
        X_seg_val,
        y_seg_val
    ),
    epochs=3,
    batch_size=4
)

#Plot Training Accuracy

plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('U-Net Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.show()

#Plot Loss Curve

plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title('U-Net Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend()

plt.show()

#Plot Dice Coefficient

plt.figure(figsize=(8,5))

plt.plot(
    history.history['dice_coefficient'],
    label='Training Dice'
)

plt.plot(
    history.history['val_dice_coefficient'],
    label='Validation Dice'
)

plt.title('Dice Coefficient')

plt.xlabel('Epoch')

plt.ylabel('Dice Score')

plt.legend()

plt.show()

#Generate Predictions

predictions = unet_model.predict(
    X_seg_val[:5]
)

#Visualize Segmentation Predictions

plt.figure(figsize=(12,12))

for i in range(5):


    # Original MRI

    plt.subplot(5,3,i*3+1)

    plt.imshow(X_seg_val[i])

    plt.title("Original MRI")

    plt.axis('off')



    # Ground Truth Mask

    plt.subplot(5,3,i*3+2)

    plt.imshow(
        y_seg_val[i].squeeze(),
        cmap='gray'
    )

    plt.title("Generated Mask")

    plt.axis('off')



    # Predicted Mask

    plt.subplot(5,3,i*3+3)

    plt.imshow(
        predictions[i].squeeze(),
        cmap='gray'
    )

    plt.title("Predicted Mask")

    plt.axis('off')

plt.tight_layout()

plt.show()

#Save U-Net Model

unet_model.save(
    'unet_brain_tumor_model.h5'
)

#TUMOR CLASSIFICATION MODEL

#Convert Labels to Categorical

from tensorflow.keras.utils import to_categorical

#One-Hot Encode Labels

y_train_cat = to_categorical(y_train, 4)

y_val_cat = to_categorical(y_val, 4)

#Build MobileNetV2 Classifier

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(96,96,3)
)

for layer in base_model.layers:
    layer.trainable = False

#Final Classification Model

x = base_model.output

x = GlobalAveragePooling2D()(x)

x = Dense(
    128,
    activation='relu'
)(x)

x = Dropout(0.5)(x)

outputs = Dense(
    4,
    activation='softmax'
)(x)

classification_model = Model(
    inputs=base_model.input,
    outputs=outputs
)

#Compile Classification Model

classification_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

#Model Summary

classification_model.summary()

#Train Classification Model

classification_history = classification_model.fit(
    X_train,
    y_train_cat,
    validation_data=(
        X_val,
        y_val_cat
    ),
    epochs=5,
    batch_size=8
)

#Plot Classification Accuracy

plt.figure(figsize=(8,5))

plt.plot(
    classification_history.history['accuracy'],
    label='Training Accuracy'
)

plt.plot(
    classification_history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.title('Classification Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.show()

#Plot Classification Loss

plt.figure(figsize=(8,5))

plt.plot(
    classification_history.history['loss'],
    label='Training Loss'
)

plt.plot(
    classification_history.history['val_loss'],
    label='Validation Loss'
)

plt.title('Classification Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend()

plt.show()

#Generate Predictions

y_pred = classification_model.predict(X_val)

y_pred_classes = np.argmax(
    y_pred,
    axis=1
)

y_true = np.argmax(
    y_val_cat,
    axis=1
)

#Confusion Matrix

cm = confusion_matrix(
    y_true,
    y_pred_classes
)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.title('Confusion Matrix')

plt.show()

#Classification Report

print(
    classification_report(
        y_true,
        y_pred_classes
    )
)

#Classification Model

classification_model.save(
    'brain_tumor_classifier.h5'
)

#One-Hot Encoder

from tensorflow.keras.utils import to_categorical

#One-Hot Encode Labels

y_train_cat = to_categorical(y_train, 4)

y_val_cat = to_categorical(y_val, 4)

print(y_train_cat.shape)
print(y_val_cat.shape)

#MobileNetV2 Base Model

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(96,96,3)
)

#Freeze Base Layers

for layer in base_model.layers:
    layer.trainable = False

#Classification Head

x = base_model.output

x = GlobalAveragePooling2D()(x)

x = Dense(
    128,
    activation='relu'
)(x)

x = Dropout(0.5)(x)

outputs = Dense(
    4,
    activation='softmax'
)(x)

classification_model = Model(
    inputs=base_model.input,
    outputs=outputs
)

#Compile Classification Model

classification_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

#Model Summary

classification_model.summary()

#Train Classification Model

classification_history = classification_model.fit(
    X_train,
    y_train_cat,
    validation_data=(
        X_val,
        y_val_cat
    ),
    epochs=5,
    batch_size=8
)

#Class Names

class_names = [
    'glioma',
    'meningioma',
    'pituitary',
    'notumor'
]

#Visualize Predictions

plt.figure(figsize=(15,12))

for i in range(9):

    plt.subplot(3,3,i+1)

    plt.imshow(X_val[i])

    pred_label = class_names[y_pred_classes[i]]

    true_label = class_names[y_true[i]]

    plt.title(
        f"Pred: {pred_label}\nTrue: {true_label}"
    )

    plt.axis('off')

plt.tight_layout()

plt.show()

